### ISSUE TITLE
[IOS] Bug when submit the app

### ISSUE THREAD

**Issue by ChakibBenssoum** [CleverTap/clevertap-unity-sdk#58]
Hello,

I'm trying to implement clevertap on IOS, but i have two issues.
The first one is when Apple try to analyse my application. I receive a mail telling me this : 

> ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/UnityFramework.framework/UnityFramework: setTitleTextColor:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

When i removed CleverTap SDK, everything works fine.

My second issue is when i try to follow the guide (step 2 for ios) 

> Add a run script to your build phases. In Xcode, go to your Targets, under your app’s name, select Build Phases after embed frameworks, add a run script phase, and set it to use /bin/sh and the [iOS script](https://github.com/CleverTap/clevertap-unity-sdk/blob/master/Plugin/CleverTapUnity/iOS/strip.sh):

i receive an error that's say 

> Command PhaseScriptExecution failed with a nonzero exit code

Please can someone help me ?

**Comment by C4SRepo** [comment]
@nzagorchev can you take a look at this one, please?

**Comment by ChakibBenssoum** [comment]
Hello @RohitKC4S , 
Sadly, i don't really have the time to build a sample project by now, but i can do it in two weeks.
However, i'm sure the issue come from CleverTap SDK. The second error appear when i strictly follow your guide and copy your script.

I tried to build on my iphone directy, but i have this error.

[IOS Error Message.txt](https://github.com/CleverTap/clevertap-unity-sdk/files/13752021/IOS.Error.Message.txt)

Maybe it can help you to find the issue.
Have a nice day, and thanks in advance !

**Comment by ChakibBenssoum** [comment]
Hello,
I'm trying to build with a simple project and for the moment, I don't achieve to do this.
Do you have any new for me? @RohitKC4S @nzagorchev 
Thanks in advance, and Happy New Year!

**Comment by nzagorchev** [comment]
Hi @ChakibBenssoum,

1. AppStore Submission - ITMS-90338: Non-public API usage: This issue is coming from the UnityFramework itself. This also  a warning and you can submit with it and the build will be accepted. You can check the following unity threads: https://forum.unity.com/threads/app-store-connect-operation-error-the-app-references-non-public-selectors.1387839/
https://forum.unity.com/threads/warning-when-uploading-xcode14-builds-to-appstoreconnect-unity-uses-private-api-2021-3-8f1.1335845/

2. Build Phase Error: Please check the scripts added to the Build Phases. Verify the script is copied correctly. Go to the Report Navigator in Xcode (last tab in the navigators ⌘9) and see if there are more details on the BuildPhase error.

3. Regarding SDWebImage error : Please check the troubleshooting guide https://github.com/CleverTap/clevertap-unity-sdk/blob/master/docs/Troubleshooting.md#ios

**Comment by ChakibBenssoum** [comment]
Hello @nzagorchev , i wanted to give you an update.

Concerning the AppStore submission, it was'nt a warning, but an error, and it came from Clevertap SDK.
When you build with Unity, you don't add CleverTap pods because the sdk contains all we need. 
But, when we do that, the clevertap sdk is compiled under UnityFramwork. The error path comes from that.

For the error itself, i worked with a swift developer, and in the script "CleverTapUnityManager.mm" a method is called setTitleTextColor.
We change the name of the method, and now everything seems to work.

Thanks for your help though, and good luck !
